###################################################

#Name: Yaniv Bronshtein
#Last Modified: 06/2/18
#
#Program Name: bronshtein_hw1.S

#Description: This program prompts the user to input
#2 integers in the specified ranges computes a value
#based on the specified formula and displays the output back to the user according to the formula :8*int1+int2-26



#Pseudocode:
#


#checkInput1(int input2){
#	if(input1 < -20)
#		return 0
#	if(input > 5)
#		return 0
#	return 1	
#}
#checkInput2(int input2){
#	if(input < 0)
#		return 1;
#	return 0;	

#}


# int main()
#{
	#while(!checkInput1){
	#	Prompt user for input1
	#
	#	call checkInput1(input1)
	#}




	#while(!checkInput2){
	#	Prompt user for input2
	#
	#	call checkInput2(input2)
	#}

#	result = (8*int1 + int2 - 26)
#	display(result)
	
#	return 0;
#}

#
#Registers:
#	$t0 for int1
#	$t1 for int2
#	$t2 for result	  	 
 		
################################################### 	